// Generated by CoffeeScript 1.7.1

/*
wz-timepicker

mimics the google calendar time picker, no date component.
returns minutes in a day
 */

(function() {
  var module;

  module = angular.module('wjz', ['template/wztimepicker.html']);

  module.factory('TimeService', function($filter) {
    var getDurationString, today;
    today = function(minutes) {
      var date;
      date = new Date();
      date.setHours(0);
      date.setMinutes(minutes, 0, 0, 0);
      return date;
    };
    getDurationString = function(minutes) {
      var amount, hours, unit;
      hours = minutes / 60;
      unit = hours < 1 ? 'min' : hours === 1 ? 'hr' : 'hrs';
      amount = hours < 1 ? hours * 60 : hours;
      return "" + amount + " " + unit;
    };
    return {

      /* API methods
       */
      getToday: function() {
        return today(0);
      },
      getDateFromMinutes: function(minutes) {
        return today(minutes);
      },
      getTimeString: function(date) {
        return $filter('date')(date, 'h:mm a');
      },
      getTimeOptions: function() {
        var date, i, timeOptions, _i;
        timeOptions = [];
        for (i = _i = 0; _i <= 47; i = ++_i) {
          date = today(i * 30);
          timeOptions.push({
            minutes: i * 30,
            string: $filter('date')(date, 'h:mm a')
          });
        }
        return timeOptions;
      },
      getDurationString: function(minutes) {
        return getDurationString(minutes);
      },
      getOffsetTimeOptions: function(offsetMinutes) {
        var date, i, minutes, timeOptions, _i;
        timeOptions = [];
        for (i = _i = 0; _i <= 47; i = ++_i) {
          minutes = i * 30;
          if (minutes > offsetMinutes) {
            date = today(i * 30);
            timeOptions.push({
              minutes: i * 30,
              string: $filter('date')(date, 'h:mm a'),
              duration: getDurationString(minutes - offsetMinutes)
            });
          }
        }
        return timeOptions;
      }
    };
  });

  module.directive('wzTimepicker', function(TimeService, $timeout) {
    return {
      restrict: 'E',
      templateUrl: 'template/wztimepicker.html',
      scope: {
        time: '=',
        offset: '='
      },
      link: function(scope, element, attrs) {

        /*
           use javascript to track when use clicks outside of TimeOptions dropdown
           if the dropdown is open, then hide it
         */
        var setDefaults;
        $(document).mouseup(function(e) {
          if (!element.is(e.target) && element.has(e.target).length === 0) {
            if (scope.showOptions) {
              scope.showOptions = false;
              scope.$apply();
            }
          }
        });
        if (scope.offset) {
          scope.timeOptions = TimeService.getOffsetTimeOptions(scope.offset);
          scope.$watch('offset', function(newValue, oldValue) {
            scope.timeOptions = TimeService.getOffsetTimeOptions(scope.offset);
            scope.time.minutes = scope.offset + 30;
            setDefaults();
          });
        } else {
          scope.timeOptions = TimeService.getTimeOptions();
        }
        setDefaults = function() {
          var t, _i, _len, _ref;
          _ref = scope.timeOptions;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            t = _ref[_i];
            if (t.minutes === scope.time.minutes) {
              scope.setTime(t);
              return;
            }
          }
        };
        scope.showOptions = false;
        scope.show = function() {
          scope.showOptions = true;

          /* 
           need a timeout to wait for the div to be visible, 
           otherwise scrollIntoView() doesn't work
           */
          $timeout(function() {}, 1);
        };
        scope.hide = function() {
          scope.showOptions = false;
        };
        scope.setTime = function(time) {
          scope.timeString = time.string;
          scope.time.string = time.string;
          scope.time.minutes = time.minutes;
          scope.showOptions = false;
        };
        setDefaults();
      }
    };
  });

  angular.module("template/wztimepicker.html", []).run([
    "$templateCache", function($templateCache) {
      return $templateCache.put("template/wztimepicker.html", "<div style=\"display:inline-block\"> <input ng-click=\"show()\" type=\"input\" ng-model=\"timeString\" size=\"8\" style=\"font-size:12px\"> <div ng-show=\"showOptions\" style=\"border:1px solid #DDD; position:absolute;z-index:1000;font-size:12px;height:130px;width:125px;overflow-y:scroll\"> <div class=\"list-group\"> <a ng-class=\"{'selected-time': time.minutes == minutes}\" ng-repeat=\"time in timeOptions\" ng-click=\"setTime(time)\" style=\"border:none;padding:2px 5px\" class=\"list-group-item\" > {{ ::time.string }} <span style=\"position:absolute;float:right\" ng-if=\"time.duration\"> &nbsp;&nbsp;({{ ::time.duration }}) </span> </a> </div> </div> </div>");
    }
  ]);

}).call(this);
